diplom/diplom/urls.py
from django.contrib import admin
from django.urls import path, include
from first import views # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('login', views.login, name='login'),
    path('movie/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('', views.movie_list, name='movie_list'),  # список фильмов

    
    path('users/', include('users.urls', namespace='users')),

]

diplom/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.profile, name='profile'),
    path('dashboard_wishlist/wishlist/<str:type>/', views.wishlist_view, name='dashboard_wishlist'),
    path('movie/<int:movie_id>/wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('watched/add/<int:movie_id>/', views.add_to_watched, name='add_to_watched'),
    path('watched/', views.watched_movies_view, name='dashboard_watched'),
    path('rate/<int:movie_id>/<str:value>/', views.rate_movie, name='rate_movie'),
    path('rated/', views.rated_movies_view, name='dashboard_rated'),
    path('purchases/', views.purchase_history, name='dashboard_purchases'),
    path('buy/<int:movie_id>/', views.buy_ticket, name='buy_ticket'),
]

diplom/first/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=255)
    genre = models.ManyToManyField('Genre')
    overview = models.TextField()
    imdb_rating = models.FloatField()
    year = models.IntegerField()
    poster_url = models.URLField()
    trailer_id = models.CharField(max_length=20,blank=True, null=True)
    
    def __str__(self):
        return self.title
    
class Feedback(models.Model):
    name = models.CharField('Имя', max_length=100)    
    email = models.EmailField('Email')    
    message = models.TextField('Сообщение')    
    create_time = models.DateTimeField('Дата отправки', auto_now_add=True)    
    
    def __str__(self):
        return f'{self.name} ({self.email}) — {self.create_time:%Y-%m-%d %H:%M}'

class Genre(models.Model):
    genre = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.genre

diplom/first/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ["name", "email", "message"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Ваше имя"}),
            "email": forms.EmailInput(attrs={"class": "form-control", "placeholder": "Ваш email"}),
            "message": forms.Textarea(attrs={"class": "form-control", "placeholder": "Ваше сообщение", "rows": 5}),
        }

diplom/first/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render  # noqa: F811
from first.models import Movie, Genre
from django.db.models import Prefetch
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from .forms import FeedbackForm
from django.core.paginator import Paginator

menu = [
        {'title': "Главная страница", 'url_name': 'movie_list'},
        {'title': "О сайте", 'url_name': 'about'},
        {'title': "Обратная связь", 'url_name': 'contact'},     
]

# Create your views here.
def index(request: HttpRequest) -> HttpResponse:
    
    date = {
        'title': 'Главная страница',
        'menu': menu
        }
    return render(request, 'first/index.html', context= date)

def about(request: HttpRequest) -> HttpResponse:
    return render(request, 'first/about.html', {'title': 'О сайте', 'menu': menu}) 

def recc(request: HttpRequest) -> HttpResponse:
    return render(request, 'first/recc.html', {'title': 'О сайте', 'menu': menu}) 

def contact(request: HttpRequest) -> HttpResponse:
    '''Если форма валидна сохраняем сообщение в БД и показываем сообщение об успехе'''
    # Создаём форму либо с данными из POST, либо пустую
    form = FeedbackForm(request.POST or None)
    success = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            success = True
            # после сохранения сбросим форму, чтобы на странице 
            # отобразилась пустая форма с сообщением об успехе
            form = FeedbackForm()
    return render(request, 'first/contact.html', 
            {
            'title': 'Обратная связь',
            'menu': menu, 
            'form': form, 
            'success': success
            }) 

def login(request: HttpRequest) -> HttpResponse:
    return render(request, 'users/login.html', {'title': 'О сайте', 'menu': menu}) 

#Рекомендательная система

# Загружаем фильмы из базы
def load_movie_data():
    # Загружаем все фильмы с жанрами
    movies = Movie.objects.prefetch_related(
        Prefetch('genre', queryset=Genre.objects.all(), to_attr='genre_list')
    ).all()
    
    movie_data = []
    
    for movie in movies:
        # Получаем список жанров фильма (объединяем их в строку)
        genres = [genre.genre for genre in movie.genre_list]
        combined = ' '.join(genres) + ' ' + movie.overview
        movie_data.append({
            'id': movie.id,
            'title': movie.title,
            'overview': movie.overview,
            'poster_url': movie.poster_url,
            'combined': combined
        })
    
    df = pd.DataFrame(movie_data)
    return df

# Получаем рекомендации
def get_recommendations(movie_id, top_n=5):
    df = load_movie_data()
    tfidf = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf.fit_transform(df['combined'])

    cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

    indices = pd.Series(df.index, index=df['id'])
    idx = indices[movie_id]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]
    movie_indices = [i[0] for i in sim_scores]

    return df.iloc[movie_indices].to_dict(orient='records')

# View: показать рекомендации для одного фильма
def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)

    recommendations = get_recommendations(movie.id)

    return render(request, 'first/movie_detail.html', 
    {
        'movie': movie,
        'recommended_movies': recommendations,
        'menu': menu,
    })
    
    
def movie_list(request):
    selected_id = request.GET.get('category')
    all_genres = Genre.objects.order_by('genre')
    
    if selected_id:
        chosen_genre = get_object_or_404(Genre, pk=selected_id)
        qs = Movie.objects.filter(genre=chosen_genre)
    else:
        chosen_genre=None
        qs = Movie.objects.all()
    query = request.GET.get('q')
    
    if query:
        qs = qs.filter(title__icontains=query)
    qs = qs.order_by('title')
    
    
    paginator = Paginator(qs, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)    
    context = {
        'page_obj': page_obj,
        'all_genres': all_genres,
        'menu': menu,
        'selected_genre': chosen_genre,
        'query': query,
    }
    return render(request, 'first/movie_list.html', context)   

diplom/first/templates/first/about.html
{% extends "base.html" %}
{% block title %}О нас{% endblock title %}

{% block content %}
<main class="container">
    <h2>О нас</h2>
    <p>Этот сайт создавался как практическая часть к выпускной квалификационной работе.</p>
    <ul>
        <li>Автор: Атоян Владислав</li>
        <li>Студент ВГТУ, ФИТКБ, Группы БПКР-211</li>
    </ul>
</main>
{% endblock content %}

diplom/first/templates/first/contact.html
{% extends "base.html" %}
{% block title %}Контакты{% endblock title %}
{% block content%}
<main class='container'>
    <h2>{{title}}</h2>
    {% if success %}
    <div class="alert alert-success">
        Спасибо! Ваше сообщение отправлено.
    </div>
    {% endif %}
    <form method="post" class="contact-form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.name.label_tag }}<br>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="form-group">
            {{ form.email.label_tag }}<br>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="form-group">
            {{ form.message.label_tag }}<br>
            {{ form.message }}
            {{ form.message.errors }}
        </div>
        <button type="submit" class="btn">Отправить</button>
        </form>
</main>
{% endblock content%}

diplom/first/templates/first/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Главная{% endblock %}

{% block content %}
<h1>Фильмы</h1>
<div class="movie-list">
    {% for movie in movies %}
        <div class="movie-card">
            <a href="{% url 'movie_detail' movie.id %}">
                <img src="{{ movie.poster_url }}" alt="{{ movie.title }}">
            </a>
            <h3>{{ movie.title }}</h3>
            <p>{{ movie.genre }}</p>
            <p>Рейтинг: {{ movie.imdb_rating }}</p>
        </div>
    {% endfor %}
</div>
{% endblock %}

diplom/first/templates/first/movie_detail.html
{% extends 'base.html' %}

{% block title %}{{ movie.title }}{% endblock %}

{% block content %}
<div class="movie-detail-container">
    <div class="movie-info_detail">
        <img class="movie-poster" src="{{ movie.poster_url }}" alt="{{ movie.title }}">
        <div class="movie-meta">
            <h1>{{ movie.title }}</h1>
            <p><strong>Жанр:</strong> 
            
            {% for genre in movie.genre.all %}
            {{ genre.genre }} {% if not forloop.last %}, {% endif %}
            {% endfor %}
                
            </p>
            <p><strong>Рейтинг:</strong> {{ movie.imdb_rating }}</p>
            <p><strong>Описание:</strong> {{ movie.overview }}</p>
        </div>
    </div>

    {% if movie.trailer_id %}
        <h3>Смотреть трейлер</h3>
        <iframe width="40% ", height="450"
        src="https://www.youtube.com/embed/{{ movie.trailer_id }}"
            frameborder="0"
            allowfullscreen>
        </iframe>
    {% endif %}
    {% if user.is_authenticated %}
        <form method="post" action="{% url 'users:add_to_wishlist' movie.id %}">
            {% csrf_token %}
            <input type='hidden' name='wishlist_type' value='home'>
            <button type="submit" class="button">Хочу посмотреть дома</button>
        </form>

            <form method="post" action="{% url 'users:add_to_wishlist' movie.id %}">
            {% csrf_token %}
            <input type='hidden' name='wishlist_type' value='cinema'>
            <button type="submit" class="button">Хочу посмотреть в кинотеатре</button>
        </form>
        <form method='post' action="{% url 'users:add_to_watched' movie.id %}">
            {% csrf_token %}
            <button type="submit" class="button">Отметить как просмотренный</button>
        </form>
        <div class="rating-buttons">
    <a href="{% url 'users:rate_movie' movie.id 'Нравится' %}" class="button">Нравится</a>
    <a href="{% url 'users:rate_movie' movie.id 'Не нравится' %}" class="button">Не нравится</a>
        </div>

    <form method="post" action="{% url 'users:buy_ticket' movie.id %}" class="ticket-form">
    {% csrf_token %}

    <div class="ticket-options">
        <select name="purchase_type" class="ticket-select">
            <option value="home">Посмотреть дома</option>
            <option value="cinema">Купить билет в кинотеатре</option>
        </select>

        <input type="number" name="quantity" value="1" min="1" class="ticket-quantity">
    </div>

    <button type="submit" class="ticket-button">Купить</button>
</form>


    
    {% else %}
    <p>
        <a href="{% url 'login' %}">Войдите</a>, чтобы добавить фильм в список
    </p>
    {% endif %}
    <hr>
    <h2>Похожие фильмы</h2>
    <hr>
    <div class="recommended-movies">
        {% for rec_movie in recommended_movies %}
            <div class="recommended-card">
                <a href="{% url 'movie_detail' rec_movie.id %}">
                    <img src="{{ rec_movie.poster_url }}" alt="{{ rec_movie.title }}">
                    <h2>{{ rec_movie.title }}</h2 >
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

diplom/first/templates/first/movie_list.html
{% extends "base.html" %}

{% block content %}
    <!--Меню жанров -->
    <nav class='genre-list'>
        <ul>
        <li>
            <a href='{% url "movie_list" %}' class="{% if not selected_genre %}active{% endif %}">
                Все жанры
            </a>
        </li>
        
        {% for genre in all_genres %}
        <li>
            <a href="{% url 'movie_list' %}?category={{ genre.id }}"
            class="{% if genre == selected_genre %}active{% endif %}">
            {{ genre.genre }}
            </a>
        </li>
        {% endfor %}
        </ul>
    </nav>
            


    <!-- Поиск фильмов  -->
    <main class="container">
        <form method="get" action="{% url 'movie_list' %}" class="search-form">
            <input type="text" name="q" placeholder="Поиск фильмов..." value="{{ request.GET.q }}">
            {% if selected_genre %}
            <input type='hidden' name='category' value='{{ selected_genre.id }}'>
            {% endif %}
            <button type="submit">Найти</button>
        </form>
    <!-- Основной блок с фильмами -->
        <h2>Фильмы</h2>
        <div class="movie-list">
            {% for movie in page_obj %}
                <div class="movie-card">
                    <img src="{{ movie.poster_url }}" alt="{{ movie.title }}">
                    <div class="movie-info">
                        <h3>{{ movie.title }}</h3>
                        <p><strong>Жанр:</strong> 
                    {% for genre in movie.genre.all %}
                            {{ genre.genre }} 
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}</p>
                        <p><strong>Описание:</strong> {{ movie.overview|truncatechars:200 }}</p>
                        <p><strong>Рейтинг IMDb:</strong> {{ movie.imdb_rating }}</p>
                        <div class="button-wrapper">
                        <a href="{% url 'movie_detail' movie.id %}" class="btn">Подробнее</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    <!-- Пагинация -->
        <div class="pagination">
            {% if page_obj.has_previous %}
                <a href="?page=1{% if selected_genre %}&category={{ selected_genre.id }}{% endif %}">&laquo; Первая</a>
                <a href="?page={{ page_obj.previous_page_number }}{% if selected_genre %}&category={{ selected_genre.id }}{% endif %}">Назад</a>
            {% endif %}
            <span class='current-page'>
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Вперед</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
            {% endif %}
        </div>
        </main>

{% endblock content %}