diplom/diplom/urls.py
from django.contrib import admin
from django.urls import path, include
from first import views # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('login', views.login, name='login'),
    path('movie/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('', views.movie_list, name='movie_list'),  # список фильмов

    
    path('users/', include('users.urls', namespace='users')),

]

diplom/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.profile, name='profile'),
    path('dashboard_wishlist/wishlist/<str:type>/', views.wishlist_view, name='dashboard_wishlist'),
    path('movie/<int:movie_id>/wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('watched/add/<int:movie_id>/', views.add_to_watched, name='add_to_watched'),
    path('watched/', views.watched_movies_view, name='dashboard_watched'),
    path('rate/<int:movie_id>/<str:value>/', views.rate_movie, name='rate_movie'),
    path('rated/', views.rated_movies_view, name='dashboard_rated'),
    path('purchases/', views.purchase_history, name='dashboard_purchases'),
    path('buy/<int:movie_id>/', views.buy_ticket, name='buy_ticket'),
]

diplom/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Wishlist(models.Model):
    wishlist_type_choises = [
        ('home', 'Смотреть дома'),
        ('cinema', 'Смотреть в кино'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey('first.Movie', on_delete=models.CASCADE)
    wishlist_type = models.CharField(max_length=20, choices=wishlist_type_choises)
    creared_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('user', 'movie', 'wishlist_type')
        
class Rating(models.Model):
    rating_choices = [
        (1, 'Нравится'),
        (2, 'Не нравится'),
    ]
    
    movie = models.ForeignKey('first.Movie', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(choices=rating_choices)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('movie', 'user')
        
class WatchedMovie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey('first.Movie', on_delete=models.CASCADE)
    watched_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('user', 'movie')
        
class Purchase(models.Model):
    PURCHASE_TYPE_CHOICES = [
        ('home', 'Просмотр дома'),
        ('cinema', 'Поход в кинотеатр'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey('first.Movie', on_delete=models.CASCADE)
    purchase_type = models.CharField(max_length=10, choices=PURCHASE_TYPE_CHOICES)
    quantity = models.PositiveIntegerField(default=1)
    price_per_ticket = models.DecimalField(max_digits=6, decimal_places=2)
    purchased_at = models.DateTimeField(auto_now_add=True)
    session_time = models.DateTimeField(null=True, blank=True)  # Только для кино

    def total_price(self):
        return self.quantity * self.price_per_ticket

    class Meta:
        ordering = ['-purchased_at']

diplom/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from .models import Wishlist
class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', 
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', 
                            widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']
        
class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput())
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'email','first_name', 'last_name','password1', 'password2']
        labels = {
            'email': 'Email',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с таким email уже существует')
        return email
    
class WishlistForm(forms.ModelForm):
    class Meta:
        model = Wishlist
        fields = ['wishlist_type']

diplom/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import LoginUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from users.forms import RegisterUserForm
from django.views.generic import CreateView
from .models import Wishlist,WatchedMovie, Rating, Purchase
from first.models import Movie
from django.contrib.auth.decorators import login_required
from decimal import Decimal
from django.utils import timezone
from datetime import timedelta
# Create your views here.

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}
    
    def get_success_url(self):
        return reverse_lazy('movie_list')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))
class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')
    
    

def register(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request,'users/register_done.html') 
    form = RegisterUserForm()
    return render(request, 'users/register.html', {'form': form})

def profile(request):
    return render(request, 'profile.html')

@login_required
def wishlist_view(request, type):
    wishlist_movie = Wishlist.objects.filter(user=request.user, wishlist_type=type).select_related('movie')
    movies = [i.movie for i in wishlist_movie]
    
    return render(request, 'users/wishlist.html', {
        'wishlist_type': type, 
        'movies': movies,
        })
    

@login_required
def add_to_wishlist(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.method == 'POST':
        wishlist_type = request.POST.get('wishlist_type')
        
        existing = Wishlist.objects.filter(user=request.user, movie=movie, wishlist_type=wishlist_type)
        if not existing.exists():
            Wishlist.objects.create(user=request.user, movie=movie, wishlist_type=wishlist_type)
    return redirect('movie_detail', movie_id=movie.id)

@login_required
def add_to_watched(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    
    WatchedMovie.objects.get_or_create(user=request.user, movie=movie)
    return redirect('movie_detail', movie_id=movie.id)

@login_required
def watched_movies_view(request):
    watched = WatchedMovie.objects.filter(user=request.user).select_related('movie')
    movies = [entry.movie for entry in watched]
    
    return render(request, 'users/watched_movies.html', {
        'movies': movies
        })
    
@login_required
def rate_movie(request, movie_id, value):
    movie = get_object_or_404(Movie, id=movie_id)
    if value not in ['Нравится', 'Не нравится']:
        return redirect('movie_detail',movie_id=movie_id)
    rating_value = 1 if value == 'Нравится' else 2
    
    Rating.objects.update_or_create(
        user=request.user,
        movie=movie,
        defaults={'rating': rating_value}
    )
    return redirect('movie_detail', movie_id=movie.id)

@login_required
def rated_movies_view(request):
    ratings = Rating.objects.filter(user=request.user).select_related('movie')
    
    return render(request, 'users/rated_movies.html', {
        'ratings': ratings
        })

@login_required
def purchase_history(request):
    purchases = Purchase.objects.filter(user=request.user).select_related('movie')
    return render(request, 'users/purchase_history.html', {'purchases': purchases})

@login_required
def buy_ticket(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        purchase_type = request.POST.get('purchase_type')
        quantity = int(request.POST.get('quantity', 1))
        price = Decimal('250.00') if purchase_type == 'cinama' else Decimal('100.00')
        
        session_time = None
        if purchase_type == 'cinama':
            session_time = timezone.now() + timedelta(days=3)
        
        Purchase.objects.create(
            user=request.user, 
            movie=movie, 
            purchase_type=purchase_type, 
            quantity=quantity, 
            price_per_ticket=price, 
            session_time=session_time
            )
        return redirect('users:dashboard_purchases')

diplom/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<h1>Авторизация</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Вход</button></p>
{% endblock content %}

diplom/users/templates/users/purchase_history.html
{% extends 'profile.html' %}

{% block dashboard_content %}
<h2>История покупок</h2>
<table class="purchase-table">
<tr>
    <th>Фильм</th>
    <th>Тип</th>
    <th>Сеанс</th>
    <th>Билеты</th>
    <th>Цена</th>
    <th>Дата покупки</th>
</tr>
{% for item in purchases %}
<tr>
    <td><a href="{% url 'movie_detail' item.movie.id %}">{{ item.movie.title }}</a></td>
    <td>{{ item.get_purchase_type_display }}</td>
    <td>{% if item.session_time %}{{ item.session_time|date:"d.m.Y H:i" }}{% else %}-{% endif %}</td>
    <td>{{ item.quantity }}</td>
    <td>{{ item.total_price }} ₽</td>
    <td>{{ item.purchased_at|date:"d.m.Y H:i" }}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

diplom/users/templates/users/rated_movies.html
{% extends 'profile.html' %}

{% block dashboard_content %}
<h2>Оценённые фильмы</h2>
<div class="movie-list">
{% for rating in ratings %}
    <div class="movie-card">
    <img src="{{ rating.movie.poster_url }}" alt="{{ rating.movie.title }}">
    <div class="movie-info">
        <h3><a href="{% url 'movie_detail' rating.movie.id %}">{{ rating.movie.title }}</a></h3>
        <p>{{ rating.movie.description|truncatewords:20 }}</p>
        <p>
        {% if rating.rating == 1 %}
        Нравится
        {% else %}
        Не нравится
        {% endif %}
        </p>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}

diplom/users/templates/users/register.html
{% extends "base.html" %}

{% block content %}
<h1>Регистрация</h1>
<form method="post">

    {% csrf_token %}
    
    {{ form.as_p }}
    
    <p><button type="submit">Регистрация</button></p>
</form>
{% endblock content %}

diplom/users/templates/users/register_done.html
{% extends "base.html" %}

{% block content %}
<h1>Регистрация завершена. Теперь Вы можете авторизоваться на сайте по 
<a href='{% url "users:login" %}'>ссылке</a>
</h1>
{% endblock content %}

diplom/users/templates/users/watched_movies.html
{% extends 'profile.html' %}

{% block dashboard_content %}
<h2>Просмотренные фильмы</h2>
<div class="movie-list">
    {% for movie in movies %}
        <div class="movie-card">
            <img src="{{ movie.poster_url }}" alt="{{ movie.title }}">
            <div class="movie-info">
                <h3><a href="{% url 'movie_detail' movie.id %}">{{ movie.title }}</a></h3>
                <p>{{ movie.description|truncatewords:20 }}</p>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

diplom/users/templates/users/wishlist.html
{% extends "profile.html" %}

{% block dashboard_content %}
<h3>
    {% if wishlist_type == 'home' %}
    Хочу посмотреть дома
    {% else %}
    Хочу посмотреть в кинотеатре
    {% endif %}
</h3>
<div class='movie-list'>
    
    {% for movie in movies  %}
    <div class="movie-card">
        <img src='{{ movie.poster_url }}' alt='{{ movie.title }}'>
        <div class="movie-info">
            <h3>{{ movie.title }}</h3>
            <p><strong>Описание:</strong> {{ movie.overview|truncatechars:200 }}</p>
            <a href='{% url "movie_detail" movie.id %}' class="btn">Подробнее</a>     
        </div>
    </div>
    {% empty %}
    <p>В вашем списке нет фильмов.</p>
    {% endfor %}
<div>
{% endblock dashboard_content %}