diplom/diplom/urls.py
from django.contrib import admin
from django.urls import path, include
from first import views # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('login', views.login, name='login'),
    path('movie/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('', views.movie_list, name='movie_list'),  # список фильмов

    
    path('users/', include('users.urls', namespace='users')),

]

diplom/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.profile, name='profile'),
    path('dashboard_wishlist/wishlist/<str:type>/', views.wishlist_view, name='dashboard_wishlist'),
    path('movie/<int:movie_id>/wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('watched/add/<int:movie_id>/', views.add_to_watched, name='add_to_watched'),
    path('watched/', views.watched_movies_view, name='dashboard_watched'),
    path('rate/<int:movie_id>/<str:value>/', views.rate_movie, name='rate_movie'),
    path('rated/', views.rated_movies_view, name='dashboard_rated'),
    path('purchases/', views.purchase_history, name='dashboard_purchases'),
    path('buy/<int:movie_id>/', views.buy_ticket, name='buy_ticket'),
]

diplom/templates/base.html
{% load static %}

<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Онлайн-кинотеатр{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'first/css/styles.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <h1>Онлайн-Кинотеатр</h1>
            <ul class="nav-links">

                {% for item in mainmenu %}
                    <li><a href="{% url item.url_name %}"> {{ item.title }} </a></li>
                {% endfor %}
                {% if user.is_authenticated %}
                <li class='last'><a href="{% url 'users:profile' %}">{{ user.username }} | <a href="{% url 'users:logout' %}">Выход</a></li>
                
                {% else %}
                <li class='last'><a href="{% url 'users:login' %}">Вход</a> | <a href='{% url "users:register" %}'>Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

diplom/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1>Личный кабинет</h1>

<div class="dashboard-menu">
    <ul>
        <li><a href="#">Настройки </a></li>
        <li><a href="{% url 'users:dashboard_wishlist' type='home' %}">Хочу смотреть дома</a></li>
        <li><a href="{% url 'users:dashboard_wishlist' type='cinema' %}">Хочу смотреть в кинотеатре</a></li>
        <li><a href="{% url 'users:dashboard_watched' %}">Просмотренные фильмы</a></li>
        <li><a href="{% url 'users:dashboard_rated' %}">Оцененные фильмы</a></li>
        <li><a href="{% url 'users:dashboard_purchases' %}">История покупок</a></li>
    </ul>
</div>

{% block dashboard_content %}


{% endblock dashboard_content %}
{% endblock content %}